### ISSUE TITLE
Device type is unknot

### ISSUE THREAD

**Issue by Kydix** [loick111/homebridge-rfxcom-accessories#10]
**Describe Your Problem:**

**Logs:**

Homebridge v1.6.0 (HAP v0.11.0) (RFXCOM) is running on port 55641.
Error: Device type 'blinds1' is unknown
    at new SwitchAccessory (/var/lib/homebridge/node_modules/homebridge-rfxcom-accessories/src/accessories/switchAccessory.ts:65:13)
    at RFXCOMAccessories.discoverSwitchDevices (/var/lib/homebridge/node_modules/homebridge-rfxcom-accessories/src/platform.ts:278:9)
    at RFXCOMAccessories.discoverDevices (/var/lib/homebridge/node_modules/homebridge-rfxcom-accessories/src/platform.ts:147:10)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-rfxcom-accessories/src/platform.ts:70:12)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.signalFinished (/var/lib/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:189:14)
[04/05/2023, 22:26:17] [RFXCOM] Child bridge process ended

**Plugin Config:**

 "name": "RFXCOM",
            "tty": "/dev/ttyUSB0",
            "debug": false,
            "discover": false,
            "devices": {
                "switch": [
                    {
                        "name": "Store",
                        "type": "blinds1",
                        "subtype": "6",
                        "id": "0000001"
                    }
                ]
            },
            "_bridge": {
                "username": "",
                "port": 
            },
            "platform": "RFXCOMAccessories"

**Environment:**

* **Plugin Version**: 2.40
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 18.13.0
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by loick111** [comment]
Hello @Kydix,
Can you try with `Blinds1` by capitalising the first letter?

**Comment by Kydix** [comment]
Thanks it’s better now. But how can I control open close and stop function ? I have only one switch now

**Comment by loick111** [comment]
Sorry, but as mentioned in the README (https://github.com/loick111/homebridge-rfxcom-accessories#switch-onoff), only devices that support on/off commands can be used with `SwitchAccessory`.

A new "accessory" would be needed to support this type of device in the plugin.
Feel free to create a pull request proposing the integration!

**Comment by Kydix** [comment]
Thanks for you answer and your help I'll create a new request
